## my global config
global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "vmagent"
    static_configs:
      - targets: [ "vmagent:8429" ]

  - job_name: "pushgateway"
    static_configs:
      - targets: [ "prometheus-pushgateway:9091"]
